// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEsroKVNz6iT6c2wGrO4rxiDZ6H5nSzdY',
    appId: '1:623546761262:web:70d91a00bd354df46edfbf',
    messagingSenderId: '623546761262',
    projectId: 'aquacare-1ce87',
    authDomain: 'aquacare-1ce87.firebaseapp.com',
    storageBucket: 'aquacare-1ce87.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr4LxJgF74gV-_lbV-4GB-GfsmeK3T7Z0',
    appId: '1:623546761262:android:44966505f7aafd536edfbf',
    messagingSenderId: '623546761262',
    projectId: 'aquacare-1ce87',
    storageBucket: 'aquacare-1ce87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXAlEeCjAvVdzeI1mqEkKqx5QqSoyybKQ',
    appId: '1:623546761262:ios:a346575c8e66527b6edfbf',
    messagingSenderId: '623546761262',
    projectId: 'aquacare-1ce87',
    storageBucket: 'aquacare-1ce87.firebasestorage.app',
    iosBundleId: 'com.example.gwapo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXAlEeCjAvVdzeI1mqEkKqx5QqSoyybKQ',
    appId: '1:623546761262:ios:a346575c8e66527b6edfbf',
    messagingSenderId: '623546761262',
    projectId: 'aquacare-1ce87',
    storageBucket: 'aquacare-1ce87.firebasestorage.app',
    iosBundleId: 'com.example.gwapo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEsroKVNz6iT6c2wGrO4rxiDZ6H5nSzdY',
    appId: '1:623546761262:web:70d91a00bd354df46edfbf',
    messagingSenderId: '623546761262',
    projectId: 'aquacare-1ce87',
    authDomain: 'aquacare-1ce87.firebaseapp.com',
    storageBucket: 'aquacare-1ce87.firebasestorage.app',
  );
}